#server
server:
  port: 8100
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csmssys?serverTimezone=GMT%2B8
    username: root
    password: passwd
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: false
  mapper-locations:
  - classpath:/mapper/*/*.xml
  
#log
logging:
  level:
    com.macrosan: DEBUG